apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "automation"
  name: "automation-configurations"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "2Gi"