replicaCount: 1

image:
  repository: "linuxserver/radarr"
  tag: "arm32v7-latest"
  pullPolicy: IfNotPresent

env:
  - name: PUID
    value: "1000"
  - name: PGID
    value: "1000"

service:
  type: ClusterIP
  port: 80

volumes:
  - name: "media-nas"
    persistentVolumeClaim:
      claimName: "media-nas"
  - name: "configurations"
    persistentVolumeClaim:
      claimName: "configurations"

volumeMounts:
  - name: "configurations"
    mountPath: "/config"
    subPath: "radarr"
  - name: "media-nas"
    mountPath: "/downloads/transmission"
    subPath: "downloads/transmission"
  - name: "media-nas"
    mountPath: "/movies"
    subPath: ""