apiVersion: v1
kind: PersistentVolume
metadata:
  name: "media-nas"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "2900Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/pi/NAS"