apiVersion: v1
kind: Service
metadata:
  labels:
    app: homeassistant
  name: homeassistant
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 8123
  selector:
    app: homeassistant
  type: LoadBalancer