apiVersion: v1
kind: PersistentVolume
metadata:
  name: "media-music"
  labels:
    type: "local"
spec:
  storageClassName: "manual"
  capacity:
    storage: "2900Gi"
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/Music"