apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: "automation"
  name: "automationconfigs"
spec:
  storageClassName: "manual"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "2Gi"